---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    cattle.io/creator: norman
  name: APP_NAME
  namespace: NAME_SPACE
spec:
  clusterIP: None
  ports:
    - name: default
      port: APP_PORT
      protocol: TCP
      targetPort: APP_PORT
  selector:
    workload.user.cattle.io/workloadselector: deployment-NAME_SPACE-APP_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-NAME_SPACE-APP_NAME
  name: APP_NAME
  namespace: NAME_SPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-NAME_SPACE-APP_NAME
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-NAME_SPACE-APP_NAME
    spec:
      containers:
        - env:
            - name: APLO_ENV
              value: APLO_ENV_VALUE
            - name: MEM_ENV
              value: MEM_ENV_VALUE
          name: APP_NAME
          image: IMAGE_TAG
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 2
            successThreshold: 1
            tcpSocket:
              port: APP_PORT
            timeoutSeconds: 2

          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 2
            successThreshold: 2
            tcpSocket:
              port: APP_PORT
            timeoutSeconds: 2
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aliyun
      restartPolicy: Always

